### ISSUE TITLE
Loading large models 

### ISSUE THREAD

**Issue by AnandMulay** [gpvigano/AsImpL#36] opened 2019-03-28 07:34 UTC
> **WARNING:** Any issue that does not follow the below template could be closed and not re-opened until the template structure is adhered to.

#### Precheck

> * For proposing a new feature, please check existing open and closed issues before creating a duplicate
> * Add comment to an issue only if related to it (otherwise choose a different issue or create a new one)
> * Please do not write long text in issue title, choose a short title for the topic, then add your text to the issue body
> * For bugs, do a quick search and make sure the bug has not yet been reported
> * Finally, follow the code of conduct (at <https://github.com/gpvigano/AsImpL/blob/master/CODE_OF_CONDUCT.md>)
> 
> **Choose one of the categories below and follow the related template (fill the coosen section, delete everything else, including this text).**

### New features and suggestions

Follow the rules above and try to be as clear as possible.

#### Environment
>Please specify:
> * version of AsImpL (Github master commit hash or at least date/hour when you downloaded it)
> * version of Unity3D (e.g. Unity 5.4.4f1)

#### Steps to reproduce

> For issues related to a specific 3D model try to identify which are the features of the model that cause the issue, or at least attach as a ZIP archive a very simple (lightweight) 3D model that has the same problem. If this is not possible you can send that model via e-mail to <gpv.code@gmail.com> with a subject starting with "*[AsImpL] 3D model-*", then you can create a related issue.

> For general bugs, attempt to recreate the issue with a simple example code and provide steps to reproduce if possible. Include code samples, errors and stacktraces if appropriate.

#### Expected behavior

> For general bugs, briefly describe what you expect should happen.

#### Current behavior

> For general bugs, briefly describe what is actually happening.

**Comment by AnandMulay** [comment] 2019-03-28 07:36
I'm working on UWP/HoloLens project  i cant load model which have size more than 70mb, any idea why this thing is happening.

**Comment by gpvigano** [comment] 2019-04-19 08:34
Sorry for this late reply, I have very limited time at the moment, and I have no more access to an HoloLens device for testing (probably later in this year). I have made a test with a model of 500MB and it worked on Windows (even if it takes more than 2 minutes to load), so I don't think the problem is related to the size itself. I also suggest to make a test on UWP/PC to see if the problem is related to UWP or HoloLens. 

And... sorry, but in the meanwhile I must close this issue because it does not contain enough information for debugging. Please create a new issue filling each section (mostly Unity version), replacing the issue instructions with proper information (maybe after testing with UWP/PC). Thank you for your interest in AsImpL and thanks in advance for your comprehension.

**Closed by gpvigano** 2019-04-19 08:34 UTC
